;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Player.CombatState.Attacking",DevComment="")
+GameplayTagList=(Tag="Player.CombatState.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="Player.CombatState.LightAttack",DevComment="")
+GameplayTagList=(Tag="Player.CombatState.Locking",DevComment="")

