;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Player.CombatState.Attacking",NewTagName="Character.CombatState.Attacking")
+GameplayTagRedirects=(OldTagName="Player.CombatState.HeavyAttack",NewTagName="Character.CombatState.HeavyAttack")
+GameplayTagRedirects=(OldTagName="Player.CombatState.LightAttack",NewTagName="Character.CombatState.LightAttack")
+GameplayTagRedirects=(OldTagName="Player.CombatState.Locking",NewTagName="Character.CombatState.Locking")
+GameplayTagRedirects=(OldTagName="Player.CombatState",NewTagName="Character.CombatState")
+GameplayTagRedirects=(OldTagName="Player.HitState.Front.Light",NewTagName="Character.HitState.Front.Light")
+GameplayTagRedirects=(OldTagName="Player.HitState.Front",NewTagName="Character.HitState.Front")
+GameplayTagRedirects=(OldTagName="Player.HitState",NewTagName="Character.HitState")
+GameplayTagRedirects=(OldTagName="Player",NewTagName="Character")
+GameplayTagRedirects=(OldTagName="Data.Effect.Poise",NewTagName="Data.Effect.PoiseDamage")
+GameplayTagList=(Tag="Character.CombatState.Defend",DevComment="")
+GameplayTagList=(Tag="Character.CombatState.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="Character.CombatState.HitStun",DevComment="")
+GameplayTagList=(Tag="Character.CombatState.LightAttack",DevComment="")
+GameplayTagList=(Tag="Character.CombatState.Roll",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Heavy",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Heavy.Back",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Heavy.Down",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Heavy.Left",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Heavy.Right",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Heavy.Up",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Light",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Light.Back",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Light.Down",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Light.Left",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Light.Right",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Light.Up",DevComment="")
+GameplayTagList=(Tag="Data.Effect.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Effect.Healing",DevComment="")
+GameplayTagList=(Tag="Data.Effect.PoiseDamage",DevComment="")
+GameplayTagList=(Tag="Event.AI.DoHeavyAttack",DevComment="")
+GameplayTagList=(Tag="Event.AI.DoLightAttack",DevComment="")
+GameplayTagList=(Tag="Event.Character.Death",DevComment="")
+GameplayTagList=(Tag="Event.Character.Defence",DevComment="")
+GameplayTagList=(Tag="Event.Character.DirectionalRoll",DevComment="")
+GameplayTagList=(Tag="Event.Character.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="Event.Character.HitReact",DevComment="")
+GameplayTagList=(Tag="Event.Character.LightAttack",DevComment="")
+GameplayTagList=(Tag="Event.Character.QuitDefence",DevComment="")
+GameplayTagList=(Tag="Event.Character.Roll",DevComment="")

