;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Player.CombatState.Attacking",NewTagName="Character.CombatState.Attacking")
+GameplayTagRedirects=(OldTagName="Player.CombatState.HeavyAttack",NewTagName="Character.CombatState.HeavyAttack")
+GameplayTagRedirects=(OldTagName="Player.CombatState.LightAttack",NewTagName="Character.CombatState.LightAttack")
+GameplayTagRedirects=(OldTagName="Player.CombatState.Locking",NewTagName="Character.CombatState.Locking")
+GameplayTagRedirects=(OldTagName="Player.CombatState",NewTagName="Character.CombatState")
+GameplayTagRedirects=(OldTagName="Player.HitState.Front.Light",NewTagName="Character.HitState.Front.Light")
+GameplayTagRedirects=(OldTagName="Player.HitState.Front",NewTagName="Character.HitState.Front")
+GameplayTagRedirects=(OldTagName="Player.HitState",NewTagName="Character.HitState")
+GameplayTagRedirects=(OldTagName="Player",NewTagName="Character")
+GameplayTagList=(Tag="Character.CombatState.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="Character.CombatState.HitStun",DevComment="")
+GameplayTagList=(Tag="Character.CombatState.LightAttack",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Back.Light",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Down.Light",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Left.Light",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Right.Light",DevComment="")
+GameplayTagList=(Tag="Character.HitState.Up.Light",DevComment="")
+GameplayTagList=(Tag="Data.Effect.Damage",DevComment="")
+GameplayTagList=(Tag="Event.AI.DoHeavyAttack",DevComment="")
+GameplayTagList=(Tag="Event.AI.DoLightAttack",DevComment="")
+GameplayTagList=(Tag="Event.Character.Death",DevComment="")
+GameplayTagList=(Tag="Event.Character.HitReact",DevComment="")

